if(NOT DEFINED PREVIEW OR NOT DEFINED FIXTURE OR NOT DEFINED TEST_DIR)
  message(FATAL_ERROR "PREVIEW, FIXTURE and TEST_DIR are required")
endif()
file(MAKE_DIRECTORY "${TEST_DIR}")
configure_file("${FIXTURE}" "${TEST_DIR}/input.csv" COPYONLY)
file(SHA256 "${TEST_DIR}/input.csv" before)
execute_process(COMMAND "${PREVIEW}" "${TEST_DIR}/input.csv" "${TEST_DIR}/./input.csv"
  RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
if(status EQUAL 0)
  message(FATAL_ERROR "Preview accepted an alias of its input")
endif()
file(SHA256 "${TEST_DIR}/input.csv" after)
if(NOT before STREQUAL after)
  message(FATAL_ERROR "Rejected input alias modified the original CSV")
endif()
execute_process(COMMAND "${PREVIEW}" "${TEST_DIR}/input.csv" "${TEST_DIR}/preview.svg" "225.5"
  RESULT_VARIABLE status ERROR_VARIABLE error)
if(NOT status EQUAL 0)
  message(FATAL_ERROR "Real solver fixture preview failed: ${error}")
endif()
file(READ "${TEST_DIR}/preview.svg" svg)
if(NOT svg MATCHES "BIOMD0000000012" OR NOT svg MATCHES "</svg>" OR NOT svg MATCHES "225.5")
  message(FATAL_ERROR "Preview does not contain expected model/time and closing SVG")
endif()
file(SHA256 "${TEST_DIR}/preview.svg" before)
foreach(invalid "nan" "inf" "-1" "12junk")
  execute_process(COMMAND "${PREVIEW}" "${TEST_DIR}/input.csv" "${TEST_DIR}/preview.svg" "${invalid}"
    RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
  if(status EQUAL 0)
    message(FATAL_ERROR "Preview accepted invalid time: ${invalid}")
  endif()
  file(SHA256 "${TEST_DIR}/preview.svg" after)
  if(NOT before STREQUAL after)
    message(FATAL_ERROR "Invalid argument damaged existing preview")
  endif()
endforeach()
file(WRITE "${TEST_DIR}/invalid.csv" "not a compatible circuit trace\n")
execute_process(COMMAND "${PREVIEW}" "${TEST_DIR}/invalid.csv" "${TEST_DIR}/preview.svg"
  RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
file(SHA256 "${TEST_DIR}/preview.svg" after)
if(status EQUAL 0 OR NOT before STREQUAL after)
  message(FATAL_ERROR "Malformed trace did not fail while preserving existing output")
endif()
message(STATUS "Actual solver fixture preview and CLI preservation checks passed")
